export const HOME_PAGE = "/"
export const CONTACT_US_PAGE = "/contact-us"
export const PAGE_NOT_FOUND = "/*"
export const OUR_WORK = "/our-work"
export const Common_Landing_Page = "/common-landing-page"
